
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://b5744e85-ac63-4823-a0a6-731fd66c5c17.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImI1NzQ0ZTg1LWFjNjMtNDgyMy1hMGE2LTczMWZkNjZjNWMxNyIsInJvbGUiOiJhbm9uIiwiaWF0IjoxNzUwNjIzMzU1LCJleHAiOjIwNjYxOTkzNTV9.oyKEwKQqsGZ2rE4VhsQQzxl7Bk5n_cWQ8Qj_1r8KsKo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
